"""Exporters: datasets, a reproducibility report, and runnable scripts.

Beyond the simulated data itself, a researcher needs to be able to *justify* and
*reproduce* it. So alongside the trial-level and cell-mean CSVs we emit:

* a human-readable reproducibility report (design, formula, priors, seed,
  convergence diagnostics, package versions), and
* the equivalent **Bambi (Python)** and **brms (R)** scripts, so the exact
  modeling pipeline is transparent and re-runnable in either ecosystem.
"""

from __future__ import annotations

import json
from textwrap import indent
from typing import Any

from .formula import build_formula, brms_formula, brms_family
from .spec import FAMILY_INFO, OutcomeFamily, StudyDesign


# --------------------------------------------------------------------------- #
# Reproducibility report
# --------------------------------------------------------------------------- #
def reproducibility_report(design: StudyDesign, *, source: str,
                           n_participants: int, seed: int,
                           diagnostics: dict[str, Any] | None = None,
                           sample_kwargs: dict[str, Any] | None = None) -> str:
    lines: list[str] = []
    a = lines.append
    a(f"# Reproducibility report: {design.name}\n")
    a("_Generated by Counterfactual Participant Studio "
      "(method after While & Sarvghad, CHI '25)._\n")

    a("## Generation summary\n")
    a(f"- Source of cell parameters: **{source}** "
      f"({'fit to your data' if source == 'posterior' else 'your stated assumptions'})")
    a(f"- Counterfactual participants generated: **{n_participants:,}**")
    a(f"- Random seed: `{seed}`")
    if sample_kwargs:
        a(f"- Sampler settings: `{json.dumps(sample_kwargs)}`")
    a("")

    a("## Study design\n")
    a(f"- Grouping unit: `{design.grouping}`")
    a(f"- Drop global intercept (cell-means coding): `{design.drop_intercept}`")
    io = design.interaction_order
    a(f"- Interaction order: `{'full' if io is None else io}`\n")
    a("### Factors\n")
    a("| Factor | Kind | Role | Levels |")
    a("| --- | --- | --- | --- |")
    for f in design.factors:
        lv = ", ".join(map(str, f.levels)) if f.levels else "(continuous)"
        a(f"| `{f.name}` | {f.kind.value} | {f.role.value} | {lv} |")
    a("")
    a("### Outcomes\n")
    a("| Outcome | Family | Notes | Trials/cell |")
    a("| --- | --- | --- | --- |")
    for o in design.outcomes:
        note = FAMILY_INFO[o.family]["label"]
        if o.family == OutcomeFamily.BERNOULLI and o.guess_rate:
            note += f", chance floor = {o.guess_rate:.0%}"
        a(f"| `{o.name}` | {o.family.value} | {note} | {o.trials_per_cell} |")
    a("")

    a("## Models\n")
    for o in design.outcomes:
        parts = build_formula(design, o)
        a(f"### `{o.name}`\n")
        a(f"- Bambi family: `{parts.bambi_family}`"
          + ("  (gaussian on `log` of the response)" if parts.needs_log_transform else ""))
        a(f"- Bambi formula: `{parts.bambi_formula}`")
        a(f"- brms formula: `{brms_formula(design, o)}`, family `{brms_family(o)}`")
        if diagnostics and o.name in diagnostics:
            d = diagnostics[o.name]
            a(f"- Convergence: **{d['status']}** "
              f"(max R-hat = {d['max_rhat']:.3f}, min bulk ESS = {d['min_ess_bulk']:.0f}, "
              f"divergences = {d['n_divergences']})")
            a(f"  - {d['interpretation']}")
        a("")

    a("## Software\n")
    a(_versions_block())
    return "\n".join(lines)


def _versions_block() -> str:
    pkgs = ["bambi", "pymc", "arviz", "pytensor", "numpy", "pandas", "scipy"]
    out = []
    for p in pkgs:
        try:
            mod = __import__(p)
            out.append(f"- {p}=={getattr(mod, '__version__', '?')}")
        except Exception:
            out.append(f"- {p}==(not installed)")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Emitted scripts
# --------------------------------------------------------------------------- #
def bambi_script(design: StudyDesign, *, seed: int = 1234,
                 draws: int = 1000, tune: int = 1000, chains: int = 4) -> str:
    """A standalone Python script reproducing the fit with Bambi."""
    blocks = ['"""Reproduce the Bayesian fit with Bambi/PyMC.',
              f'Design: {design.name}',
              'Generated by Counterfactual Participant Studio."""',
              "import numpy as np, pandas as pd, bambi as bmb, arviz as az",
              "",
              'df = pd.read_csv("your_data.csv")  # long format: one row per trial',
              ""]
    cats = [f.name for f in design.categorical_factors] + [design.grouping]
    blocks.append(f"for col in {cats!r}:")
    blocks.append("    df[col] = df[col].astype('category')")
    blocks.append("")
    for o in design.outcomes:
        parts = build_formula(design, o)
        if parts.needs_log_transform:
            blocks.append(f'df["log_{o.name}"] = np.log(df["{o.name}"])')
    blocks.append("")
    for o in design.outcomes:
        parts = build_formula(design, o)
        if o.family == OutcomeFamily.BERNOULLI and o.guess_rate:
            blocks.append(_chance_family_snippet(o.guess_rate))
            fam = "fam"
        else:
            fam = f'"{parts.bambi_family}"'
        var = o.name.replace("-", "_")
        blocks.append(
            f'model_{var} = bmb.Model("{parts.bambi_formula}", df, family={fam})'
        )
        blocks.append(
            f"idata_{var} = model_{var}.fit(draws={draws}, tune={tune}, "
            f"chains={chains}, random_seed={seed}, target_accept=0.9)"
        )
        blocks.append(f"print(az.summary(idata_{var}))")
        blocks.append("")
    return "\n".join(blocks)


def _chance_family_snippet(guess: float) -> str:
    g = guess
    return indent(
        f"""# Chance-corrected Bernoulli: p = {g} + {1 - g:.2f} * inv_logit(eta)
import pytensor.tensor as pt
from scipy.special import expit, logit
_g = {g}
fam = bmb.Family(
    "chance_bernoulli",
    likelihood=bmb.Likelihood("Bernoulli", parent="p"),
    link={{"p": bmb.Link(
        "chance",
        link=lambda mu: logit((np.asarray(mu) - _g) / (1 - _g)),
        linkinv=lambda eta: _g + (1 - _g) * expit(np.asarray(eta)),
        linkinv_backend=lambda eta: _g + (1 - _g) * pt.sigmoid(eta),
    )}},
)""", "")


def brms_script(design: StudyDesign, *, seed: int = 1234,
                draws: int = 2000, chains: int = 6) -> str:
    """A standalone R script reproducing the fit with brms (as in the paper)."""
    lines = [f"# Reproduce the Bayesian fit with brms (after While & Sarvghad, CHI '25).",
             f"# Design: {design.name}",
             "library(brms)",
             'df <- read.csv("your_data.csv")  # long format: one row per trial',
             ""]
    cats = [f.name for f in design.categorical_factors] + [design.grouping]
    for c in cats:
        lines.append(f'df${c} <- as.factor(df${c})')
    lines.append("")
    warmup = max(1000, draws // 2)
    for o in design.outcomes:
        f = brms_formula(design, o)
        fam = brms_family(o)
        var = o.name.replace("-", "_")
        lines.append(f'fit_{var} <- brm(')
        lines.append(f'  bf({f}),')
        lines.append(f'  data = df, family = {fam},')
        lines.append(f'  chains = {chains}, iter = {draws + warmup}, warmup = {warmup},')
        lines.append(f'  seed = {seed}, control = list(adapt_delta = 0.9)')
        lines.append(")")
        lines.append(f"summary(fit_{var})")
        lines.append("")
    return "\n".join(lines)


def design_to_json(design: StudyDesign) -> str:
    return json.dumps(design.to_dict(), indent=2)
